refactor: usersSerivce, usersRepository, user directory
42Seoul-LastDance/Main pull request #8
Opened 2023-08-25 12:08 UTC by ebang091

userRepository 생성 후 userService 에 의존성 주입하였습니다.

## 요약

<br><br>

## 작업 내용
 user directory 내 관련 소스코드 위치시켰습니다.
 userService searchOne(name) 메소드를 getUserByName(name) 수정 후 NotFoundException 추가하였습니다.
<br><br>

## 참고 사항

<br><br>

## 관련 이슈

- Close #이슈번호

<br><br>

comment 남겨주시면 참고 하겠습니다!

2023-08-25 15:47 UTC, Tolerblanc requested changes
.vscode 폴더가 같이 커밋 됐어요!!

2023-08-25 15:47 UTC, Tolerblanc commented on .vscode/settings.json
이상한 친구가 따라 들어왔습니다...

2023-08-28 06:55 UTC, ebang091 commented on .vscode/settings.json
지웠습니다!

2023-08-28 07:05 UTC, Tolerblanc approved these changes

2023-08-28 07:12 UTC, OZestina requested changes
srcs/nest/src/user/users.service.ts 에 수정할 부분 코멘트 남겨두었습니다!

2023-08-28 07:12 UTC, OZestina commented on srcs/nest/src/user/users.service.ts
기존 33~37줄의 코드는
- 검색하려고 하는 name으로 시작하는 name을 가진 모든 유저를 (Like(`${name}%`))
- 사전 순으로 가져오는 (name: 'ASC') 코드였습니다.
이 부분은 기존 코드대로 가면 좋을 것 같아요!

2023-08-28 07:13 UTC, ebang091 commented on srcs/nest/src/user/users.service.ts
알려주셔서 감사합니다! 제가 파악을 잘못했었네요!
이름을 getUserListByFirstSlackid 로 하고, slackId 로 검색하게 구현해도 될까요?

2023-08-28 07:14 UTC, OZestina commented on srcs/nest/src/user/users.service.ts
네 좋습니다!

2023-08-28 07:22 UTC, OZestina approved these changes

2023-08-28 07:23 UTC, merged